# Generated by Django 3.0.3 on 2020-03-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
