# Generated by Django 3.0.3 on 2020-03-24 07:35

from django.db import migrations


def capitalize(apps,schema_editor):
    Product = apps.get_model('main','Product')
    for product in Product.objects.all():
        product.name = product.name.capitalize()
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimage_thumbnail'),
    ]

    operations = [
        migrations.RunPython(
            capitalize,
            migrations.RunPython.noop
        ),
    ]
